/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StackRouteImport } from './routes/stack'
import { Route as PlayBreakoutRouteImport } from './routes/play/breakout'
import { Route as PlayDodgeRouteImport } from './routes/play/dodge'
import { Route as PlaySnakeRouteImport } from './routes/play/snake'
import { Route as PlayTetrisRouteImport } from './routes/play/tetris'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBreakoutRoute = PlayBreakoutRouteImport.update({
  id: '/play/breakout',
  path: '/play/breakout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDodgeRoute = PlayDodgeRouteImport.update({
  id: '/play/dodge',
  path: '/play/dodge',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySnakeRoute = PlaySnakeRouteImport.update({
  id: '/play/snake',
  path: '/play/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTetrisRoute = PlayTetrisRouteImport.update({
  id: '/play/tetris',
  path: '/play/tetris',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stack': typeof StackRoute
  '/play/breakout': typeof PlayBreakoutRoute
  '/play/dodge': typeof PlayDodgeRoute
  '/play/snake': typeof PlaySnakeRoute
  '/play/tetris': typeof PlayTetrisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stack': typeof StackRoute
  '/play/breakout': typeof PlayBreakoutRoute
  '/play/dodge': typeof PlayDodgeRoute
  '/play/snake': typeof PlaySnakeRoute
  '/play/tetris': typeof PlayTetrisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stack': typeof StackRoute
  '/play/breakout': typeof PlayBreakoutRoute
  '/play/dodge': typeof PlayDodgeRoute
  '/play/snake': typeof PlaySnakeRoute
  '/play/tetris': typeof PlayTetrisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stack'
    | '/play/breakout'
    | '/play/dodge'
    | '/play/snake'
    | '/play/tetris'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stack'
    | '/play/breakout'
    | '/play/dodge'
    | '/play/snake'
    | '/play/tetris'
  id:
    | '__root__'
    | '/'
    | '/stack'
    | '/play/breakout'
    | '/play/dodge'
    | '/play/snake'
    | '/play/tetris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StackRoute: typeof StackRoute
  PlayBreakoutRoute: typeof PlayBreakoutRoute
  PlayDodgeRoute: typeof PlayDodgeRoute
  PlaySnakeRoute: typeof PlaySnakeRoute
  PlayTetrisRoute: typeof PlayTetrisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/breakout': {
      id: '/play/breakout'
      path: '/play/breakout'
      fullPath: '/play/breakout'
      preLoaderRoute: typeof PlayBreakoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/dodge': {
      id: '/play/dodge'
      path: '/play/dodge'
      fullPath: '/play/dodge'
      preLoaderRoute: typeof PlayDodgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/snake': {
      id: '/play/snake'
      path: '/play/snake'
      fullPath: '/play/snake'
      preLoaderRoute: typeof PlaySnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/tetris': {
      id: '/play/tetris'
      path: '/play/tetris'
      fullPath: '/play/tetris'
      preLoaderRoute: typeof PlayTetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StackRoute: StackRoute,
  PlayBreakoutRoute: PlayBreakoutRoute,
  PlayDodgeRoute: PlayDodgeRoute,
  PlaySnakeRoute: PlaySnakeRoute,
  PlayTetrisRoute: PlayTetrisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
